language: node_js
sudo: false
node_js:
- stable
- 4.2
script:
- npm run ci
after_success:
- cat ./build/reports/coverage/coverage.lcov | node_modules/coveralls/bin/coveralls.js
after_failure:
- for file in *.log; do echo $file; echo "======================"; cat $file; done
  || true
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: D9vS8VvhziKHvlI5so4pBiM/b0yeclKn0d1WWG0bIcMqlnfH7Q3PvYXBRRqfyI09w1s3QDQ5OSYrZUp2RRKtGLt2rQNz/1I7yNNWTFOnWn4LnR6gREIRHeNJgHuDaiQrz9lZ0BgdOfCCn/D9PnQgtTtQsJngZQq0GPs+repBeM1OK/XfBe3bsdoTQCTnhO9RLse1H4B4McZQ9SRx5x82SOyNo76MTiIc1vsaOwH3jYTnSE52d1HML982PVabocGGsQrroY/iFC+2XhSyFH/DwgMNKyl4LMbwruMtXxhzxGmK2lds8jEbgjezhNtlZwrsv39NE2gyibzp0DidvTDfEk5UKKN18Oac1THJiChpRJ7C4PTjPHzQgG+qZ3oj+Pt45nKwgzXyn0n8RlhefnWOHfcb7mmHNVL6f+dJtCYKJInbZxHOUCR1/5FmBnW0Z2Z/xhnCcw48TLTDMg8jrH6YlZbuuUn58fLP/vdxxat1PEJLra7bvyuPwgsnYw72YmivFAMkZpabX0rRwLzULeVoB5INjTn9rtIKbvQEP22vc/41nkn1KrkAmZio3G9MW/apHfGuJAkMAMNtS8E31BMHCRjHrf5ILA9btke2QSRXcJeXP4Q6u04HUCO6yxgFdC8k+ILC0LU+ykdvsWgHpP/nGfQrqWOjKh2xtRV59t8jZpk=
  skip_cleanup: true
  on:
    branch: master
    tags: true
