language: node_js
sudo: false
node_js:
- 4.2
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
# - ./test/shell_scripts/run_tests.sh
after_success:
- cat ./build/reports/coverage/coverage.lcov | node_modules/coveralls/bin/coveralls.js
after_failure:
- for file in *.log; do echo $file; echo "======================"; cat $file; done
  || true
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: D9vS8VvhziKHvlI5so4pBiM/b0yeclKn0d1WWG0bIcMqlnfH7Q3PvYXBRRqfyI09w1s3QDQ5OSYrZUp2RRKtGLt2rQNz/1I7yNNWTFOnWn4LnR6gREIRHeNJgHuDaiQrz9lZ0BgdOfCCn/D9PnQgtTtQsJngZQq0GPs+repBeM1OK/XfBe3bsdoTQCTnhO9RLse1H4B4McZQ9SRx5x82SOyNo76MTiIc1vsaOwH3jYTnSE52d1HML982PVabocGGsQrroY/iFC+2XhSyFH/DwgMNKyl4LMbwruMtXxhzxGmK2lds8jEbgjezhNtlZwrsv39NE2gyibzp0DidvTDfEk5UKKN18Oac1THJiChpRJ7C4PTjPHzQgG+qZ3oj+Pt45nKwgzXyn0n8RlhefnWOHfcb7mmHNVL6f+dJtCYKJInbZxHOUCR1/5FmBnW0Z2Z/xhnCcw48TLTDMg8jrH6YlZbuuUn58fLP/vdxxat1PEJLra7bvyuPwgsnYw72YmivFAMkZpabX0rRwLzULeVoB5INjTn9rtIKbvQEP22vc/41nkn1KrkAmZio3G9MW/apHfGuJAkMAMNtS8E31BMHCRjHrf5ILA9btke2QSRXcJeXP4Q6u04HUCO6yxgFdC8k+ILC0LU+ykdvsWgHpP/nGfQrqWOjKh2xtRV59t8jZpk=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: KshEOlSNvHFze/OIOtJIxbEoPmzhWtui9xjIt4+ozfqp11FtYNnxURLMYHpCt+uESQOmhFFPINHyyQ7Dmai9qDnMnEqv7dKBBSooG57fzIpghZMWIn13VJr5UP64w88J1jPT0nMnWwBc4OFUYJy6PKTaI48BGiZ28RbXiuXOD1XXG9W3HmMF/eJGTzrfMOD7erxKt9UGPlIHYYNKefA9ZWAmU7osK5UEwSTKNME/z3i+orl9gQjyFqydUOmUxDHP04nr7jkSC1S+pfyuQwWl6bFf5teGDE5Pnl+RXB4r42plFpNk449wMz/lBblXpbOOFIjnH612sebtRIA8ZpKZMeePc56UUTzrBoidiEmpKCI7Z5P+Wfddaa1ms+BeOmFFu21kCFmvpd7jTrtH8J8b0Sy9Azn3va2+XwScBF22kDzwXUMk1uOS4ETeO9IpUN6fH0bjs2oThxgtmmc+64jS5jdz8ecdowCicFd1FtZ1OiI3TKEuDMRbBsg/60CBiKy5aVGUGNnd5G8YSfTM/eZPSjdcuk3YF78cww8LOu1scnphY7Po43RQde/oJUXnEynMo0S3q4m9E4ReRFGRTYHUl/A1XwAC79y+n0P+cbc6BBXNCKHX7L5DRtQjGOy+MaWky/ZDhf7c0r7VkpRapzCze9N7tsVAWaaJqpU3jQrmQsY=
